version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

  eureka:
    build:
      context: ./BE/eureka  # BE 폴더에서 Dockerfile을 참조
      dockerfile: Dockerfile  # Dockerfile 지정 (생략 가능)
    container_name: eureka
    hostname: eureka  # 컨테이너 내부에서 사용할 이름
    environment:
      - SERVER_PORT=45000
      - SPRING_APPLICATION_NAME=eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=eureka  # 컨테이너 내부 통신을 위해 eureka로 설정
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:45000/eureka/
    networks:
      - app_network
    restart: always
    ports:
      - "45000:45000"

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
