version: '3.8'


services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
