# 1. OpenJDK 기반 이미지 사용
FROM openjdk:17-jdk-slim

# 2. 작업 디렉토리 설정
WORKDIR /app

# 3. 빌드된 JAR 파일 복사
COPY build/libs/eureka-service-0.0.1-SNAPSHOT.jar app.jar

# 5. JAR 실행 (디버그 모드 포함)
CMD ["java", "-jar", "/app/app.jar"]

# 6. 포트 노출 (애플리케이션 + 디버깅)
EXPOSE 45001
