spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://nas.shnea.kr:45021/postgres
    username: postgres
    password: "!Bcsic123"
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    dbcp2:
      connection-init-sqls: SET TIMEZONE TO 'Asia/Seoul'
      test-on-borrow: true
      validation-query: SELECT 1
    tomcat:
      max-active: 300
      max-idle: 100
      max-wait: 10000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: "shpark91.iptime.org"
      port: 45020
      password: "!Bcsic123"