server:
  port: 45003

spring:
  application:
    name: comm-service

  datasource:
    url: jdbc:log4jdbc:postgresql://nas.shnea.kr:45021/postgres
    username: postgres
    password: "!Bcsic123"
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    dbcp2:
      connection-init-sqls: SET TIMEZONE TO 'Asia/Seoul'
      test-on-borrow: true
      validation-query: SELECT 1
    tomcat:
      max-active: 300
      max-idle: 100
      max-wait: 10000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    openfeign:
      enabled: true  # Feign 사용
      httpclient:
        enabled: true  # 최신 HttpClient 사용
  data:
    redis:
      host: redis
      port: 45020

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}  # 고유 ID 보장
    hostname: ${spring.application.name}  # 서비스 이름을 호스트네임으로 사용
    prefer-ip-address: true


jwt:
  secret: 7696df8573fd07575d6debf0c10c51719d64c9402e43da5665f2dc3868107762
  authHeader: Authorization
  refreshHeader: RefreshAuth
  type: Bearer