server:
  port: 45000

spring:
  jwt :
    secret : 7696df8573fd07575d6debf0c10c51719d64c9402e43da5665f2dc3868107762
    type : Bearer
  application:
    name: gateway-service
  profiles:
    active: local  # 기본적으로 로컬 환경을 사용

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:45000"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-login
          uri: lb://auth-service
          predicates:
            - Path=/auth/login
          filters:
            - name: AuthenticationFilter
              args:
                baseMessage: Test 설정입니다.
        - id: test-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}


logging:
  level:
    bcs : debug
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG